app_admin_documentos:
    resource: "@AppBundle/Resources/config/routing/documento.yml"
    prefix:   /admin/documentos

app_admin_users:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix:   /admin/users
    
app_admin_category:
    resource: "@AppBundle/Resources/config/routing/category.yml"
    prefix:   /admin/category
    
app_admin_trabajo:
    resource: "@AppBundle/Resources/config/routing/trabajo.yml"
    prefix:   /admin/data

homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

publicaciones_genericos:
    path:     /cat/{slug}.html
    defaults: { _controller: AppBundle:Default:genericos }

descargar_archivo:
    path:     /{id}/descargar.html
    defaults: { _controller: AppBundle:Default:downloadOriginalFile }

documento:
    path:     /documento/{slug}.html
    defaults: { _controller: AppBundle:Default:documento }

sitiosinteres:
    path:     /sitios-interes.html
    defaults: { _controller: AppBundle:Default:sitiosinteres }

otrosmateriales:
    path:     /otros-materiales.html
    defaults: { _controller: AppBundle:Default:otrosmateriales }   

colaboradores:
    path:     /colaboradores.html
    defaults: { _controller: AppBundle:Default:colaboradores }

buscador:
    path:     /buscar.html
    defaults: { _controller: AppBundle:Default:buscar }