#FosUserBundle Routes
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#maith routes    
maith_common_translator:
    resource: "@MaithCommonTranslatorBundle/Resources/config/routing.yml"
    prefix:   /

maith_common_image:
    resource: "@MaithCommonImageBundle/Resources/config/routing.yml"
    prefix:   /

maith_common_admin:
    resource: "@MaithCommonAdminBundle/Resources/config/routing.yml"
    prefix:   /    

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /    