admin_documentos_index:
    path:     /
    defaults: { _controller: "AppBundle:Documento:index" }
    methods:  GET

admin_documentos_new:
    path:     /new
    defaults: { _controller: "AppBundle:Documento:new" }
    methods:  [GET, POST]

admin_documentos_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Documento:edit" }
    methods:  [GET, POST]

admin_documentos_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Documento:delete" }
    methods:  DELETE
