admin_monografiaposgrado_index:
    path:     /
    defaults: { _controller: "AppBundle:Monografiaposgrado:index" }
    methods:  GET

admin_monografiaposgrado_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Monografiaposgrado:show" }
    methods:  GET

admin_monografiaposgrado_new:
    path:     /new
    defaults: { _controller: "AppBundle:Monografiaposgrado:new" }
    methods:  [GET, POST]

admin_monografiaposgrado_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Monografiaposgrado:edit" }
    methods:  [GET, POST]

admin_monografiaposgrado_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Monografiaposgrado:delete" }
    methods:  DELETE
