admin_monografiagrado_index:
    path:     /
    defaults: { _controller: "AppBundle:Monografiagrado:index" }
    methods:  GET

admin_monografiagrado_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Monografiagrado:show" }
    methods:  GET

admin_monografiagrado_new:
    path:     /new
    defaults: { _controller: "AppBundle:Monografiagrado:new" }
    methods:  [GET, POST]

admin_monografiagrado_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Monografiagrado:edit" }
    methods:  [GET, POST]

admin_monografiagrado_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Monografiagrado:delete" }
    methods:  DELETE
